#basic workflow

name: CI

# mention events when action will run

on:
  #Trigger workflow on push or pull request event but only for master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  #Allow to run this workflow manually from actions tab
  workflow_dispatch:

#A workflow run made of one or more jobs that can be run sequiential or parralel manner
jobs:
  #this workflow contains single job called "build"
#  lint:
#    # type of runner that job will run on
#    runs-on: ubuntu-latest
#
#    #Steps represent sequence of tasks that will be executed as part of job
#    steps:
#      #Checkout your repository under
#      - name: Checkout branch
#        uses: actions/checkout@v2
#
#      #Runs a single command by single shell
#      - name: Run Lint
#        run: ./gradlew lintDebug
#
#      #Runs a single command by single shell
#      - name: Upload html test report
#        uses: actions/upload-artifact@v2
#        with:
#          name: lint.html
#          path: app/build/reports/lint-results-debug.html
#
#  test-cases:
#    needs: [lint]
#    runs-on: ubuntu-latest
#
#    steps:
#      - name : Checkout branch
#        uses : actions/checkout@v2
#
#      - name: Run Unit Test Cases
#        run: ./gradlew test
#
#      - name: Upload test results
#        uses: actions/upload-artifact@v2
#        with:
#          name: test.html
#          path: app/build/reports/tests/testDebugUnitTest/

  static-code-analysis:
    #needs: [test-cases]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: setUp JDK 11
        uses: actions/setup-java@v1
        with:
           java-version: 11

      - name: Sonar Cloud Scan
        run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_QUBE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
